### ISSUE TITLE
The way Users who create comics are stored

### ISSUE THREAD

**Issue by Bsabz** [www-purple/Mixxy#105]
Regarding: #103, I think Im having problems with this because of how Comic.java Kind is structured. We should take in a parameter of users creating comics but this Ref<k> datatype doesn't allow me to statically refer to that entity. 

I might have to resort to using `public List<Long> authorIds;` to store the author of the comics. 
Then in the constructor for Comics take in a parameter called `final User author`, initializing `this.authorIds = Lists.newArrayList(author.id);` in the constructor. Any thoughts on this approach guys?

**Comment by Bsabz** [comment]
Note: This could help resolve other issues regarding using the `Ref<key>` datatype.

**Comment by JesseTG** [comment]
What exactly do you mean by "users creating comics"?  You mean what the DAO asks for?

**Comment by Bsabz** [comment]
Not just that, what's more important is how the Entity is structured to store information. Comic is ***not storing any information at all*** when it comes to the User who created it, since there are no parameters in the Comic constructor for a parent User who created that Comic. We aren't creating a User field in the Comic object to retrieve. 

If you notice in the Article.java file under models, you see that the first parameter for the constructor is `final User author` and initializes it to a list of ID's for the relevant authors. We aren't doing that for Comic..

**Comment by JesseTG** [comment]
See beyond the constructors.  Those are for us, not for Objectify.  The real issue at hand is the set of properties.

I'm not sold on your argument for storing `long`s, but one thing *did* just come to mind now; how far does the graph stretch?  If I get a single `User`, should I load *all* of his/her `Comic`s?  *And* their parents?  And said parent's authors?  And said author's other comics?  And...

So, on further consideration, yes, just store the IDs.  Make sure the relevant DAOs have a way to get objects from them, though.
