### ISSUE TITLE
Investigate a backend framework

### ISSUE THREAD

**Issue by JesseTG** [www-purple/Mixxy#12]
My vote is still on Ninja, but I'd like to do a bit more homework on that

**Comment by JesseTG** [comment]
Leaning towards it more.  Not many other lightweight Java web frameworks support Google App Engine, unfortunately.  But I'll still hear thoughts on it until Monday.

**Comment by Bsabz** [comment]
Im for Ninja as well.

**Comment by JesseTG** [comment]
Ninja it is.
