### ISSUE TITLE
Settle once and for all; tabs or spaces?  How many of them?

### ISSUE THREAD

**Issue by JesseTG** [www-purple/Mixxy#138]
I'm starting to see inconsistent indentation, and it's getting confusing having to keep up different conventions between files.  But I don't wanna dictate something that's sometimes controversial.

So I'll reformat all the code, but I wanna hear opinions on indentation.  My vote goes to increments of two spaces, no tabs.  Thoughts?

**Comment by k-cleary** [comment]
I like tabs

**Comment by Bsabz** [comment]
Tabs

**Comment by JesseTG** [comment]
Ok.  @cristianomj indicated in person that he prefers tabs, too, so we'll do that.  After today I'll send a big-ass PR that reformats all of the code (and while I'm at it, I'll probably add another static analysis tool to enforce a style guide).  Case closed.  :ship:
