### ISSUE TITLE
Formalize the data requirements

### ISSUE THREAD

**Issue by JesseTG** [www-purple/Mixxy#4]
What do we need to store?  This would entail ER diagrams, possibly database schemas, etc.

**Comment by Bsabz** [comment]
Update: Will just need to specify the technologies being used for storing data in this section, not necessarily creating diagrams yet since we aren't at that stage according to McKenna

**Comment by JesseTG** [comment]
Maybe just a high-level overview of what we need to juggle (images, users, etc.)?
