### ISSUE TITLE
Model the data we need

### ISSUE THREAD

**Issue by JesseTG** [www-purple/Mixxy#49]
We bounced ideas back and forth, mostly about Firebase vs. GAE's Datastore.  But we need to figure out what we actually need to store.  The SRS is a good starting point, but I bet there's an assload of edge cases or technicalities that aren't visible from its high-level treatment.  That's where you come in.

**Comment by Bsabz** [comment]
I have created a link for you guys to look at my progress for the ER Diagram and edit as you see fit. I will make the final changes to the diagram and create a pull request to merge into our SDD. The link can be found [here](https://drive.google.com/file/d/0BxS9PI9CNMk9Mm9KQXlqZTVWRVk/view?usp=sharing).

**Comment by JesseTG** [comment]
Coming along quite nicely, I think we're almost ready to turn this into code (just gotta tie up loose ends regarding OAuth/Disqus/DA integration).
