### ISSUE TITLE
Figure out how to turn database info into Java objects and back

### ISSUE THREAD

**Issue by JesseTG** [www-purple/Mixxy#50]
[Ninja](http://www.ninjaframework.org/) seems to be pretty agnostic about that, but the [App Engine archetype](https://github.com/ninjaframework/ninja-appengine/) and [JPA support](http://www.ninjaframework.org/documentation/working_with_relational_dbs/jpa.html) ought to be useful.  Post your findings here.

**Comment by Bsabz** [comment]
We can model and retrieve the data using JPA like you said, using Guise Persist which is a JPA library used by GAE. This is used to persist the data in the database: [https://github.com/google/guice/wiki/GoogleAppEngine](https://github.com/google/guice/wiki/GoogleAppEngine)

For modeling the data we can use the JavaEE standard persist shown here: [https://docs.oracle.com/javaee/7/tutorial/persistence-intro.htm](https://docs.oracle.com/javaee/7/tutorial/persistence-intro.htm) 

and examples given on the Ninja website here:
[http://www.ninjaframework.org/documentation/working_with_relational_dbs/jpa.html](http://www.ninjaframework.org/documentation/working_with_relational_dbs/jpa.html)

**Comment by JesseTG** [comment]
What about Objectify, didn't you say you had liked that?

**Comment by Bsabz** [comment]
I think objectify is good, but Im still trying to find the one we can get most comfortable with as soon as possible. Since we are using Ninja framework, they recommended Guise and JPA for data persist if we do a relational database, but they also mentioned Ofy service and Objectify so I'll have to look into that.

**Comment by Bsabz** [comment]
Reference to GAE support for Ninja: [https://github.com/ninjaframework/ninja-appengine](https://github.com/ninjaframework/ninja-appengine)

**Comment by JesseTG** [comment]
Look at #60; I just cloned that archetype, including the relevant data/persistence code.

**Comment by Bsabz** [comment]
Can we merge that PR or you are still waiting on the decision made here before you merge?

**Comment by JesseTG** [comment]
Waiting on at least two people to look it over and give it the OK

**Comment by JesseTG** [comment]
As we discussed on Skype, this is the [DAO](https://en.wikipedia.org/wiki/Data_access_object) (data access object)/DTO (data transfer object) pattern applied.  The nice thing is that we can basically turn our data needs right into actual classes.  There are several examples in the archetype that describe the details, so we can just use those for reference.  Closing.
