### ISSUE TITLE
Sketch out an API design, and a way to implement it

### ISSUE THREAD

**Issue by JesseTG** [www-purple/Mixxy#52]
You mentioned something about a service that GAE provides that'll help us do this.  Can you elaborate more on that?

Also, [routing](http://www.ninjaframework.org/documentation/basic_concepts/basic_concepts.html) and [argument extractors](http://www.ninjaframework.org/documentation/basic_concepts/argument_extractors.html) appear to be important for this sort of thing.

**Comment by JesseTG** [comment]
@cristianomj Have you managed to look more into this?

**Comment by cristianomj** [comment]
@JesseTG I looked at this when I worked on the Tic Tac Toe hw. I'll look more into it starting tomorrow.

**Comment by JesseTG** [comment]
@cristianomj What are your thoughts on it?  What you learned, etc.
