### ISSUE TITLE
Get comfy with Apache Freemarker

### ISSUE THREAD

**Issue by JesseTG** [www-purple/Mixxy#55]
Ninja provides a [basic overview](http://www.ninjaframework.org/documentation/html_templating/getting_started.html) of how exactly the templating works, but the [full docs are right here](http://freemarker.incubator.apache.org/).  Once #35 is resolved, you can probably start playing around with actually implementing styles and whatnot.

**Comment by k-cleary** [comment]
Looks good. It seems really simple to use. I'm gonna close this issue because I feel comfortable enough with it for not (although of course I'm sure I'll need to refer back to documentation as the project goes on)
