### ISSUE TITLE
Put together a draft class diagram

### ISSUE THREAD

**Issue by JesseTG** [www-purple/Mixxy#57]
It doesn't need to be fancy, polished, or all that well-designed.  We'll all be working on that together, but looks like you're best-suited for building the starting point (since you'll be modeling the data).  After that, we can all spit-shine it and flesh out the details together.

We can split up the class diagram into multiple smaller diagrams if need be.  In fact, that's probably a good sign if the smaller diagrams stand (more or less) alone!

**Comment by JesseTG** [comment]
@Bsabz You're using draw.io, right?  Can you post the link if you've started?

**Comment by Bsabz** [comment]
Haven't started yet, been really busy at home and with 376. I will start hopefully later tonight or tomorrow after my all day interview.

**Comment by JesseTG** [comment]
Ok.  Have you thought about #50 at all, at least?  This probably depends on that, above all.

**Comment by JesseTG** [comment]
As we discussed on Skype, how we handle our integrations with Disqus, DeviantArt, and OAuth may impact our class architecture, and definitely our data needs.  You and @cristianomj will need to work together to figure out how to play nicely with those platforms, as that's our main challenge with planning our data.
