### ISSUE TITLE
Figure out how to index everything in GAE

### ISSUE THREAD

**Issue by JesseTG** [www-purple/Mixxy#77]
We need to figure out how exactly the user should be able to search for stuff.  But, more generally, we need to decide how to index all of our data so that we can do what we need to do without using up lots of memory.  There will be limits on advanced search, for example...but what are those limits?

**Comment by Bsabz** [comment]
https://cloud.google.com/datastore/docs/concepts/indexes?hl=en_US&_ga=1.7586997.604534746.1459727761

**Comment by JesseTG** [comment]
How will you apply this to Mixxy?

**Comment by Bsabz** [comment]
I placed it there for a reference...will deal with it soon
