### ISSUE TITLE
Data technology: Objectify or Google SQL?

### ISSUE THREAD

**Issue by JesseTG** [www-purple/Mixxy#8]
Discuss here, but let's decide as soon as possible (because this is mission-critical)

**Comment by Bsabz** [comment]
Need to look into:

- [ ] Objectify

- [ ] Google SQL

- [ ] BaaS (Back-end as a Service)... if McKenna allows us to use anything other than Google Datastore. 

Afterwards I'll make my final decision.

**Comment by JesseTG** [comment]
Mind elaborating a bit?

**Comment by Bsabz** [comment]
> "You can access the Datastore using the low-level API described throughout the Datastore documentation, which provides direct access to all of Datastore's features, or you can use one of the higher-level open-source APIs for Datastore that provide ORM-like features and a more abstract experience, such as Objectify. Note that while the low-level Datastore API is provided and supported by Google, Objectify is provided by a third-party, and Google does not provide support for it."

Source: ([https://cloud.google.com/appengine/docs/java/datastore/](url))

**Comment by JesseTG** [comment]
So this gives you finer control over data, right?

**Comment by Bsabz** [comment]
Yes.

**Comment by JesseTG** [comment]
And you mentioned that you can fall back to coarse-grained control via Objectify as necessary?  If so, then this works for me.

**Comment by Bsabz** [comment]
Yup, sounds good. We are set here.
